In [3]:
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np

# from geofeather.pygeos import to_geofeather, from_geofeather

import pandas as pd
import geopandas as gpd

#import pygeos
from rasterstats import zonal_stats
from scipy.stats import spearmanr
import shapely

from shapely.geometry import mapping, shape
from shapely import wkb

In [38]:
# Set paths
cisi_index_path = r"C:\Users\Gebruiker\Desktop\Thesis\FutureCISI-main\FutureCISI-main\data\010_degree\CISI_europe.feather"
# cisi_index_path = "Users\Gebruiker\Desktop\Thesis\FutureCISI-main\FutureCISI-main\data\CISI_europe.feather"
cisi_index_clip_path = 'data/CISI_exposure_Global.feather'

cisi_index_path
# Read data CISI index
cisi_index = pd.read_feather(cisi_index_path)
cisi_index_clip = pd.read_feather(cisi_index_path)
cisi_index_clip.head(3)

,CISI,Subscore_energy,Subscore_transportation,Subscore_water,Subscore_waste,Subscore_telecommunication,Subscore_healthcare,Subscore_education,geometry
0,0.015926,0.000000,0.014159,0.000000,0.000106,0.00000,0.000603,0.001058,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...
1,0.000216,0.000000,0.000216,0.000000,0.000000,0.00000,0.000000,0.000000,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...
2,0.039630,0.002892,0.025552,0.000002,0.000012,0.00131,0.004327,0.005535,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...

In [39]:
# Set paths Pop v2 dataset

#2010
world_pop_2010_SSP2_merkens = "data/output/resample/clipped_pop_2010.tif"
world_pop_2010_SSP1 = "data/population_v2/SSP1_2010_EU_UK.tif"
world_pop_2010_SSP2 = "data/population_v2/SSP2_2010_EU_UK.tif"
world_pop_2010_SSP3 = "data/population_v2/SSP3_2010_EU_UK.tif"
world_pop_2010_SSP4 = "data/population_v2/SSP4_2010_EU_UK.tif"
world_pop_2010_SSP5 = "data/population_v2/SSP5_2010_EU_UK.tif"

In [40]:
print(world_pop_2010_SSP1)

data/population_v2/SSP1_2010_EU_UK.tif

In [41]:
print("data/output/corr_v2/CISI_exposure_clip_with_pop_v2.feather")

data/output/corr_v2/CISI_exposure_clip_with_pop_v2.feather

In [42]:
test = pd.read_feather("data\output\corr_v2\CISI_exposure_clip_with_pop_v2.feather")

test.head(5)

,CISI,Subscore_energy,Subscore_transportation,Subscore_water,Subscore_waste,Subscore_telecommunication,Subscore_healthcare,Subscore_education,geometry,total_pop_2010_SSP2_merkens,total_pop_2030_SSP1,total_pop_2030_SSP2,total_pop_2030_SSP3,total_pop_2030_SSP4,total_pop_2030_SSP5
21,0.000522,0.0,0.000448,0.0,0.0,0.000000,0.0,0.000074,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,0,5.883265,6.736431,4.800498,5.883192,8.151936
22,0.000480,0.0,0.000480,0.0,0.0,0.000000,0.0,0.000000,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,0,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.003821,0.0,0.003821,0.0,0.0,0.000000,0.0,0.000000,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,0,286.529602,285.688934,284.598236,284.315033,289.102478
24,0.004880,0.0,0.002915,0.0,0.0,0.001965,0.0,0.000000,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,0,643.459839,641.342407,639.952759,639.905762,647.569336
25,0.000081,0.0,0.000081,0.0,0.0,0.000000,0.0,0.000000,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,0,0.000000,0.000000,0.000000,0.000000,0.000000